### ISSUE TITLE
Fatal Error with phpunit 9

### ISSUE THREAD

**Issue by RyanPrice-King** [mheap/phpunit-github-actions-printer#12]
PHP Fatal error:  Class mheap\GithubActionsReporter\Printer cannot extend from interface PHPUnit\TextUI\ResultPrinter in /var/www/vendor/mheap/phpunit-github-actions-printer/src/Printer.php on line 93

When I downgrade phpunit/phpunit to 8.5.2 from 9.0.1, it works fine again.

**Comment by mheap** [comment]
I released v1.3.0 yesterday which resolves this 👍
