### ISSUE TITLE
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException

### ISSUE THREAD

**Issue by ajtrichards** [mheap/phpunit-github-actions-printer#15]
Hello.

I've added this package to composer and it works fine if I have any errors in PHPUnit. When I don't have any errors, I get the following:

```
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.
```

I'm testing against PHP7.2 and PHPUnit 7.5.20

Run vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer --configuration phpunit.xml

Has anyone else experienced this error?

**Comment by mheap** [comment]
I can't seem to replicate this. This is what I did:

Bootstrap a project:

```
laravel new test && cd test
composer require --dev mheap/phpunit-github-actions-printer
```

Run the tests:

```
❯ ./vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.

::error file=tests/Feature/ExampleTest.php,line=17::RuntimeException: No application encryption key has been specified.
```

Generate a key:

```
php artisan key:generate
```

Run the test:

```
❯ ./vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.
```

Everything worked fine for me. Do you have any more details?

**Comment by mheap** [comment]
Closing due to no response
