### ISSUE TITLE
v1.3.0 is not working: class does not exist

### ISSUE THREAD

**Issue by tristanbes** [mheap/phpunit-github-actions-printer#19]
Hello

When running the printer `v1.3.0`:

<img width="1340" alt="app_condictio___srv_app" src="https://user-images.githubusercontent.com/346010/92718909-b9eec900-f362-11ea-80f7-dc3eccf74e2e.png">

Could not use "mheap\GithubActionsReporter\Printer" as printer: class does not exist

When running the printer `v1.2.0` it's working well:

<img width="1662" alt="app_condictio___srv_app" src="https://user-images.githubusercontent.com/346010/92719078-eefb1b80-f362-11ea-86d3-317aaf69cfb8.png">

**Comment by mheap** [comment]
Version 1.4.0 has been released with support for PHPUnit 7

**Comment by tristanbes** [comment]
Thanks
