### ISSUE TITLE
Cannot send session cache limiter - headers already sent

### ISSUE THREAD

**Issue by staabm** [mheap/phpunit-github-actions-printer#4]
We have some test using session_start() etc and because of the output created by this result printer we run into `Cannot send session cache limiter - headers already sent` errors.

Not sure why this does not happen with the default result printer... maybe you print to early or something?

https://github.com/redaxo/redaxo/pull/3172/checks?check_run_id=397516031

**Comment by staabm** [comment]
I guess the reason could be that https://github.com/mheap/phpunit-github-actions-printer/blob/master/src/Printer.php#L52 contains a newline and therefore output might get flush'ed immediately

**Comment by mheap** [comment]
@staabm Could you try with `v1.1.0`? There was a bug with some errors that caused a warning which would have written to `stdout`
